

CREATE SEQUENCE SEQ_CHK;
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, TO_DATE('18/01/01')+SEQ_CHK.CURRVAL, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, SEQ_BNO2.NEXTVAL, 'TEST - '||SEQ_CHK.NEXTVAL||' - ', '테스트 용 샘플 데이터 입니다.' || SEQ_CHK.CURRVAL, 'user01', DEFAULT, NULL, DEFAULT, DEFAULT);

COMMIT;